sudo: required
services:
    - dcoker

before_install:
  - docker build -t rohit2627/docker-react-travis-aws -f Dockerfile.dev . 

script:
   - docker run -e CI=true rohit2627/docker-react-travis-aws npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-travis-aws"
  env: "DockerReactTravisAws-env"
  bucket_name: "elasticbeanstalk-us-east-1-710327008523"
  bucket_path: "docker-react-travis-aws"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  




